### ISSUE TITLE
ERROR JVoiceXmlSession:365 - error processing application 'Unknown application'

### ISSUE THREAD

**Issue by mzamoun** [hotblac/voicexmlriot#1]
Hi,

When I run in JUnit the DemoIT.java, I get this error : 

2018-02-19 10:57:43,915 INFO  JVoiceXmlMain:120 - ----------------------------------------------------
2018-02-19 10:57:43,919 INFO  JVoiceXmlMain:121 - starting VoiceXML interpreter 0.7.7.GA...
2018-02-19 10:57:43,920 INFO  JVoiceXmlMain:129 - interpreter state STARTED
2018-02-19 10:57:43,920 INFO  JVoiceXmlMain:313 - interpreter state ALLOCATING_RESOURCES
2018-02-19 10:57:43,921 INFO  JVoiceXmlMain:327 - using configuration 'org.vxmlriot.jvoicexml.EmbeddedTextConfiguration'
2018-02-19 10:57:43,922 DEBUG JVoiceXmlMain:536 - added shutdown hook
2018-02-19 10:57:43,929 INFO  JVoiceXmlDocumentServer:313 - adding scheme strategy for scheme 'http': org.jvoicexml.documentserver.schemestrategy.HttpSchemeStrategy
2018-02-19 10:57:43,929 INFO  JVoiceXmlDocumentServer:313 - adding scheme strategy for scheme 'file': org.jvoicexml.documentserver.schemestrategy.FileSchemeStrategy
2018-02-19 10:57:43.953:INFO::JVoiceXmlMain: Logging initialized @343ms
2018-02-19 10:57:43.978:INFO:oejs.Server:JVoiceXmlMain: jetty-9.2.2.v20140723
2018-02-19 10:57:44.155:INFO:oejs.ServerConnector:JVoiceXmlMain: Started ServerConnector@145fed85{HTTP/1.1}{0.0.0.0:9595}
2018-02-19 10:57:44.155:INFO:oejs.Server:JVoiceXmlMain: Started @550ms
2018-02-19 10:57:44,155 INFO  DocumentStorage:75 - document storage started on port 9595
2018-02-19 10:57:44,164 DEBUG KeyedResourcePool:91 - loading resources of type 'text'...
2018-02-19 10:57:44,166 INFO  PoolableResourceFactory:74 - created a new resource of type (org.jvoicexml.implementation.text.TextSynthesizedOutput)
2018-02-19 10:57:44,167 DEBUG KeyedResourcePool:97 - ...resources loaded.
2018-02-19 10:57:44,167 INFO  JVoiceXmlImplementationPlatformFactory:224 - added synthesized output factory class org.jvoicexml.implementation.text.TextSynthesizedOutputFactory for type 'text'
2018-02-19 10:57:44,168 DEBUG KeyedResourcePool:91 - loading resources of type 'text'...
2018-02-19 10:57:44,172 INFO  PoolableResourceFactory:74 - created a new resource of type (org.jvoicexml.implementation.text.TextSpokenInput)
2018-02-19 10:57:44,172 DEBUG KeyedResourcePool:97 - ...resources loaded.
2018-02-19 10:57:44,174 INFO  JVoiceXmlImplementationPlatformFactory:244 - added user input factory class org.jvoicexml.implementation.text.TextSpokenInputFactory for type 'text'
2018-02-19 10:57:44,174 DEBUG KeyedResourcePool:91 - loading resources of type 'text'...
2018-02-19 10:57:44,176 INFO  PoolableResourceFactory:74 - created a new resource of type (org.jvoicexml.implementation.text.TextTelephony)
2018-02-19 10:57:44,176 DEBUG TextTelephony:397 - passivating...
2018-02-19 10:57:44,176 DEBUG TextTelephony:422 - ...passivated
2018-02-19 10:57:44,176 DEBUG KeyedResourcePool:97 - ...resources loaded.
2018-02-19 10:57:44,176 INFO  JVoiceXmlImplementationPlatformFactory:262 - added telephony factory class org.jvoicexml.implementation.text.TextTelephonyFactory for type 'text'
2018-02-19 10:57:44,177 INFO  JVoiceXmlImplementationPlatformFactory:151 - available synthesizers:
2018-02-19 10:57:44,177 INFO  JVoiceXmlImplementationPlatformFactory:154 - - 1 instance(s) of type 'text'
2018-02-19 10:57:44,177 INFO  JVoiceXmlImplementationPlatformFactory:162 - available recognizers:
2018-02-19 10:57:44,178 INFO  JVoiceXmlImplementationPlatformFactory:165 - - 1 instance(s) of type 'text'
2018-02-19 10:57:44,178 INFO  JVoiceXmlImplementationPlatformFactory:173 - available telephones:
2018-02-19 10:57:44,178 INFO  JVoiceXmlImplementationPlatformFactory:176 - - 1 instance(s) of type 'text'
2018-02-19 10:57:44,178 DEBUG KeyedResourcePool:91 - loading resources of type 'text'...
2018-02-19 10:57:44,178 INFO  PoolableResourceFactory:74 - created a new resource of type (org.jvoicexml.implementation.text.TextSynthesizedOutput)
2018-02-19 10:57:44,178 DEBUG KeyedResourcePool:97 - ...resources loaded.
2018-02-19 10:57:44,178 INFO  JVoiceXmlImplementationPlatformFactory:224 - added synthesized output factory class org.jvoicexml.implementation.text.TextSynthesizedOutputFactory for type 'text'
2018-02-19 10:57:44,178 DEBUG KeyedResourcePool:91 - loading resources of type 'text'...
2018-02-19 10:57:44,179 INFO  PoolableResourceFactory:74 - created a new resource of type (org.jvoicexml.implementation.text.TextSpokenInput)
2018-02-19 10:57:44,179 DEBUG KeyedResourcePool:97 - ...resources loaded.
2018-02-19 10:57:44,179 INFO  JVoiceXmlImplementationPlatformFactory:244 - added user input factory class org.jvoicexml.implementation.text.TextSpokenInputFactory for type 'text'
2018-02-19 10:57:44,179 DEBUG KeyedResourcePool:91 - loading resources of type 'text'...
2018-02-19 10:57:44,179 INFO  PoolableResourceFactory:74 - created a new resource of type (org.jvoicexml.implementation.text.TextTelephony)
2018-02-19 10:57:44,179 DEBUG TextTelephony:397 - passivating...
2018-02-19 10:57:44,179 DEBUG TextTelephony:422 - ...passivated
2018-02-19 10:57:44,179 DEBUG KeyedResourcePool:97 - ...resources loaded.
2018-02-19 10:57:44,179 INFO  JVoiceXmlImplementationPlatformFactory:262 - added telephony factory class org.jvoicexml.implementation.text.TextTelephonyFactory for type 'text'
2018-02-19 10:57:44,179 INFO  JVoiceXmlImplementationPlatformFactory:151 - available synthesizers:
2018-02-19 10:57:44,180 INFO  JVoiceXmlImplementationPlatformFactory:154 - - 1 instance(s) of type 'text'
2018-02-19 10:57:44,180 INFO  JVoiceXmlImplementationPlatformFactory:162 - available recognizers:
2018-02-19 10:57:44,180 INFO  JVoiceXmlImplementationPlatformFactory:165 - - 1 instance(s) of type 'text'
2018-02-19 10:57:44,180 INFO  JVoiceXmlImplementationPlatformFactory:173 - available telephones:
2018-02-19 10:57:44,180 INFO  JVoiceXmlImplementationPlatformFactory:176 - - 1 instance(s) of type 'text'
2018-02-19 10:57:44,183 INFO  GrammarIdentifierCentral:208 - added grammar identifier class org.jvoicexml.interpreter.grammar.identifier.SrgsXmlGrammarIdentifier for type 'application/srgs+xml'
2018-02-19 10:57:44,197 INFO  JVoiceXmlMain:439 - added profile 'VoiceXML21'
2018-02-19 10:57:44,197 INFO  JVoiceXmlMain:447 - available profiles:
2018-02-19 10:57:44,197 INFO  JVoiceXmlMain:450 - - 'VoiceXML21'
2018-02-19 10:57:44,198 INFO  JVoiceXmlMain:364 - interpreter state RUNNING
2018-02-19 10:57:44,199 INFO  JVoiceXmlMain:365 - VoiceXML interpreter 0.7.7.GA started.
2018-02-19 10:57:44,201 DEBUG ShutdownWaiter:68 - initialized shutdown sequence
2018-02-19 10:57:44,211 DEBUG CallBuilder:72 - Waiting for TextServer startup
2018-02-19 10:57:44,224 INFO  TextServer:312 - text server started at port '4242'
2018-02-19 10:57:44,224 DEBUG LoggingTextListener:25 - started
2018-02-19 10:57:44,225 DEBUG CallBuilder:74 - TextServer started
2018-02-19 10:57:44,226 DEBUG JVoiceXmlMain:191 - creating new session...
2018-02-19 10:57:44,238 INFO  JVoiceXmlMain:206 - created session 9771a5d1-46ff-442c-96ca-b554f01428e3
2018-02-19 10:57:44,243 DEBUG ResponseListener:60 - clear
2018-02-19 10:57:44,319 INFO  VoiceXmlInterpreterContext:272 - loaded data model 'org.jvoicexml.interpreter.datamodel.ecmascript.EcmaScriptDataModel@4efc7d7e'
2018-02-19 10:57:44,326 INFO  JVoiceXmlDocumentServer:232 - loading document with URI 'http://localhost:9090/voicexmlriot-junit-demo/start.vxml...
2018-02-19 10:57:44,342 DEBUG HttpSchemeStrategy:160 - connecting to 'http://localhost:9090/voicexmlriot-junit-demo/start.vxml'...
2018-02-19 10:57:44,610 DEBUG BasicClientConnectionManager:161 - Get connection for route {}->http://localhost:9090
2018-02-19 10:57:44,622 DEBUG DefaultClientConnectionOperator:177 - Connecting to localhost:9090
2018-02-19 10:57:45,624 DEBUG DefaultClientConnectionOperator:198 - Connect to localhost:9090 timed out. Connection will be retried using another IP address
2018-02-19 10:57:45,625 DEBUG DefaultClientConnectionOperator:177 - Connecting to localhost:9090
2018-02-19 10:57:46,627 DEBUG DefaultClientConnection:180 - Connection org.apache.http.impl.conn.DefaultClientConnection@21c7ff2e closed
2018-02-19 10:57:46,628 DEBUG DefaultClientConnection:164 - Connection org.apache.http.impl.conn.DefaultClientConnection@21c7ff2e shut down
2018-02-19 10:57:46,628 DEBUG BasicClientConnectionManager:200 - Releasing connection org.apache.http.impl.conn.ManagedClientConnectionImpl@1758a68a
2018-02-19 10:57:46,630 ERROR JVoiceXmlSession:365 - error processing application 'Unknown application'
org.jvoicexml.event.error.BadFetchError: error.badfetch: Connection refused: connect
	at org.jvoicexml.documentserver.schemestrategy.HttpSchemeStrategy.getInputStream(HttpSchemeStrategy.java:183)
	at org.jvoicexml.documentserver.JVoiceXmlDocumentServer.getDocument(JVoiceXmlDocumentServer.java:236)
	at org.jvoicexml.interpreter.VoiceXmlInterpreterContext.acquireVoiceXmlDocument(VoiceXmlInterpreterContext.java:758)
	at org.jvoicexml.interpreter.VoiceXmlInterpreterContext.loadDocument(VoiceXmlInterpreterContext.java:714)
	at org.jvoicexml.interpreter.JVoiceXmlSession.run(JVoiceXmlSession.java:361)
Caused by: java.net.ConnectException: Connection refused: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
	at java.net.PlainSocketImpl.connect(Unknown Source)
	at java.net.SocksSocketImpl.connect(Unknown Source)
	at java.net.Socket.connect(Unknown Source)
	at org.apache.http.conn.scheme.PlainSocketFactory.connectSocket(PlainSocketFactory.java:121)
	at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:180)
	at org.apache.http.impl.conn.ManagedClientConnectionImpl.open(ManagedClientConnectionImpl.java:326)
	at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:610)
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:445)
	at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:835)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
	at org.jvoicexml.documentserver.schemestrategy.HttpSchemeStrategy.getInputStream(HttpSchemeStrategy.java:173)
	... 4 more
2018-02-19 10:57:46,635 INFO  JVoiceXmlSession:422 - finished processing application 'Unknown application'
2018-02-19 10:57:46,636 INFO  JVoiceXmlSession:427 - closing session...

Can You help me please ?
Mourad From Paris

**Comment by hotblac** [comment]
Are you running this from a Maven build or from a separate JUnit instance, say in your IDE?

If you're running this _integration_ test from an IDE, you'll need to start the voicexmlriot-junit-demo application so that it's got something to connect to and test. The simplest way to start the application is from Maven command line:

`mvn tomcat7:run`

**Comment by mzamoun** [comment]
Thanks for your response.

I have 2 questions :  
1) In external commande, I play the junit tests with : mvn clean install. But not with mvn test. Why ?
2) when the tests are executed, i have this error : 
2018-02-19 12:39:48,691 DEBUG TextSenderThread:102 - trying to take next message
2018-02-19 12:39:48,691 INFO  TextServer:376 - read TextMessage[ACK, 0, null]
2018-02-19 12:39:48,691 DEBUG LoggingTextListener:50 - disconnected
2018-02-19 12:39:48,691 INFO  TextServer:521 - text server stopped
2018-02-19 12:39:49,192 INFO  JVoiceXmlSession:264 - initiating a hangup event
2018-02-19 12:39:49,192 INFO  JVoiceXmlEventHandler:560 - notified event 'connection.disconnect.hangup'
2018-02-19 12:39:49,192 INFO  JVoiceXmlSession:296 - waiting for end of session...
2018-02-19 12:39:49,192 DEBUG JVoiceXmlEventHandler:449 - received event: org.jvoicexml.event.plain.ConnectionDisconnectHangupEvent: connection.disconnect.hangup
2018-02-19 12:39:49,192 INFO  JVoiceXmlImplementationPlatform:809 - recognition stopped
2018-02-19 12:39:49,192 INFO  JVoiceXmlImplementationPlatform:815 - will stop call recording
2018-02-19 12:39:49,192 INFO  JVoiceXmlImplementationPlatform:821 - done stop record request
2018-02-19 12:39:49,192 DEBUG TextTelephony:159 - added pending message 16
2018-02-19 12:39:49,192 DEBUG DtmfInputThread:95 - reading DTMF interrupted
2018-02-19 12:39:49,192 INFO  BufferedDtmfInput:238 - stopped DTMF recognition
2018-02-19 12:39:49,193 DEBUG JVoiceXmlImplementationPlatform:350 - waiting for non-barge-in played...
2018-02-19 12:39:49,193 DEBUG JVoiceXmlImplementationPlatform:356 - ...non-barge-in played.
2018-02-19 12:39:49,192 DEBUG TextSenderThread:107 - sending TextMessage[INPUT_CLOSED, 16, null]
2018-02-19 12:39:49,193 DEBUG AbstractInputItem:93 - incrementing event counter for 'answer'...
2018-02-19 12:39:49,193 DEBUG EventCounter:71 - incremented count of 'connection.disconnect.hangup' to 1
2018-02-19 12:39:49,193 DEBUG EventCounter:71 - incremented count of 'connection.disconnect' to 1
2018-02-19 12:39:49,193 DEBUG EventCounter:71 - incremented count of 'connection' to 1
2018-02-19 12:39:49,193 DEBUG JVoiceXmlEventHandler:480 - processing event of type 'connection.disconnect.hangup'...
2018-02-19 12:39:49,193 DEBUG EventTypeFilter:68 - found 0 matching event strategies for type 'connection.disconnect.hangup'
2018-02-19 12:39:49,193 INFO  JVoiceXmlEventHandler:497 - no matching strategy for type 'connection.disconnect.hangup'
2018-02-19 12:39:49,193 DEBUG FormInterpretationAlgorithm:441 - caught JVoiceXML event while processing 'connection.disconnect.hangup'
2018-02-19 12:39:49,194 INFO  JVoiceXmlEventHandler:560 - notified event 'connection.disconnect.hangup'
2018-02-19 12:39:49,194 DEBUG AbstractInputItem:93 - incrementing event counter for 'answer'...
2018-02-19 12:39:49,194 DEBUG EventCounter:71 - incremented count of 'connection.disconnect.hangup' to 2
2018-02-19 12:39:49,194 DEBUG EventCounter:71 - incremented count of 'connection.disconnect' to 2
2018-02-19 12:39:49,194 DEBUG EventCounter:71 - incremented count of 'connection' to 2
2018-02-19 12:39:49,194 DEBUG JVoiceXmlEventHandler:480 - processing event of type 'connection.disconnect.hangup'...
2018-02-19 12:39:49,194 DEBUG EventTypeFilter:68 - found 0 matching event strategies for type 'connection.disconnect.hangup'
2018-02-19 12:39:49,194 INFO  JVoiceXmlEventHandler:497 - no matching strategy for type 'connection.disconnect.hangup'
2018-02-19 12:39:49,194 DEBUG JVoiceXmlEventHandler:390 - removed 5 event strategies for form item 'answer'
2018-02-19 12:39:49,194 INFO  ScopeObserver:106 - exiting scope 'dialog'...
2018-02-19 12:39:49,194 DEBUG ScopeObserver:120 - current scope stack: [SESSION, APPLICATION, DOCUMENT]
2018-02-19 12:39:49,194 DEBUG ActiveGrammarSet:176 - removed 1 grammars - 0 grammars remaining
2018-02-19 12:39:49,194 DEBUG GrammarDeactivator:75 - deactivating 1 grammars...
2018-02-19 12:39:49,195 DEBUG GrammarDeactivator:79 - ...1 grammars deactivated
2018-02-19 12:39:49,195 INFO  VoiceXmlInterpreterContext:571 - user hung up. terminating processing
2018-02-19 12:39:49,195 INFO  ScopeObserver:106 - exiting scope 'document'...
2018-02-19 12:39:49,195 DEBUG ScopeObserver:120 - current scope stack: [SESSION, APPLICATION]
2018-02-19 12:39:49,195 INFO  VoiceXmlInterpreterContext:580 - no more documents to process for 'Unknown application'
2018-02-19 12:39:49,195 INFO  ScopeObserver:106 - exiting scope 'application'...
2018-02-19 12:39:49,195 DEBUG ScopeObserver:120 - current scope stack: [SESSION]
2018-02-19 12:39:49,196 INFO  JVoiceXmlSession:422 - finished processing application 'Unknown application'
2018-02-19 12:39:49,196 INFO  JVoiceXmlSession:427 - closing session...
2018-02-19 12:39:49,196 INFO  JVoiceXmlImplementationPlatform:526 - closing implementation platform
2018-02-19 12:39:49,196 DEBUG JVoiceXmlImplementationPlatform:332 - waiting for empty output queue...
2018-02-19 12:39:49,196 DEBUG TextSynthesizedOutput:308 - output queue is empty
2018-02-19 12:39:49,196 DEBUG JVoiceXmlImplementationPlatform:338 - ...output queue empty.
2018-02-19 12:39:49,196 DEBUG JVoiceXmlImplementationPlatform:564 - waiting for empty input not busy...
2018-02-19 12:39:49,196 DEBUG JVoiceXmlImplementationPlatform:580 - ...input not busy.
2018-02-19 12:39:49,196 INFO  JVoiceXmlImplementationPlatform:552 - returning aqcuired resources
2018-02-19 12:39:49,196 DEBUG JVoiceXmlImplementationPlatform:284 - returning system output of type 'text'...
2018-02-19 12:39:49,196 DEBUG JVoiceXmlImplementationPlatform:735 - returning external resource 'text' (org.jvoicexml.implementation.text.TextSynthesizedOutput) to pool...
2018-02-19 12:39:49,196 DEBUG JVoiceXmlImplementationPlatform:737 - disconnecting external resource.
2018-02-19 12:39:49,196 DEBUG JVoiceXmlImplementationPlatform:741 - ...disconnected
2018-02-19 12:39:49,196 INFO  KeyedResourcePool:158 - returned object of type 'text' (org.jvoicexml.implementation.text.TextSynthesizedOutput)
2018-02-19 12:39:49,196 DEBUG KeyedResourcePool:164 - pool has now 0 active/1 idle for key 'text' (org.jvoicexml.implementation.text.TextSynthesizedOutput) after return
2018-02-19 12:39:49,196 INFO  JVoiceXmlImplementationPlatform:750 - returned external resource 'text' (org.jvoicexml.implementation.text.TextSynthesizedOutput) to pool
2018-02-19 12:39:49,196 INFO  JVoiceXmlImplementationPlatform:293 - returned system output of type 'text'
2018-02-19 12:39:49,197 DEBUG JVoiceXmlImplementationPlatform:418 - returning user input of type 'text'...
2018-02-19 12:39:49,197 DEBUG JVoiceXmlImplementationPlatform:735 - returning external resource 'text' (org.jvoicexml.implementation.text.TextSpokenInput) to pool...
2018-02-19 12:39:49,197 DEBUG JVoiceXmlImplementationPlatform:737 - disconnecting external resource.
2018-02-19 12:39:49,197 DEBUG JVoiceXmlImplementationPlatform:741 - ...disconnected
2018-02-19 12:39:49,197 INFO  KeyedResourcePool:158 - returned object of type 'text' (org.jvoicexml.implementation.text.TextSpokenInput)
2018-02-19 12:39:49,197 DEBUG KeyedResourcePool:164 - pool has now 0 active/1 idle for key 'text' (org.jvoicexml.implementation.text.TextSpokenInput) after return
2018-02-19 12:39:49,197 INFO  JVoiceXmlImplementationPlatform:750 - returned external resource 'text' (org.jvoicexml.implementation.text.TextSpokenInput) to pool
2018-02-19 12:39:49,197 INFO  JVoiceXmlImplementationPlatform:426 - returned user input of type 'text'
2018-02-19 12:39:49,197 DEBUG JVoiceXmlImplementationPlatform:502 - returning call control of type 'text'...
2018-02-19 12:39:49,197 DEBUG JVoiceXmlImplementationPlatform:735 - returning external resource 'text' (org.jvoicexml.implementation.text.TextTelephony) to pool...
2018-02-19 12:39:49,197 DEBUG JVoiceXmlImplementationPlatform:737 - disconnecting external resource.
2018-02-19 12:39:49,197 DEBUG TextTelephony:489 - disconnecting from 'tcp://EISI-MZ:4242'...
2018-02-19 12:39:49,195 DEBUG TextSenderThread:127 - error sending text message: TextMessage[INPUT_CLOSED, 16, null]
java.net.SocketException: Software caused connection abort: socket write error
	at java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.net.SocketOutputStream.socketWrite(Unknown Source)
	at java.net.SocketOutputStream.write(Unknown Source)
	at java.io.ObjectOutputStream$BlockDataOutputStream.drain(Unknown Source)
	at java.io.ObjectOutputStream$BlockDataOutputStream.setBlockDataMode(Unknown Source)
	at java.io.ObjectOutputStream.writeNonProxyDesc(Unknown Source)
	at java.io.ObjectOutputStream.writeClassDesc(Unknown Source)
	at java.io.ObjectOutputStream.writeOrdinaryObject(Unknown Source)
	at java.io.ObjectOutputStream.writeObject0(Unknown Source)
	at java.io.ObjectOutputStream.writeFatalException(Unknown Source)
	at java.io.ObjectOutputStream.writeObject(Unknown Source)
	at org.jvoicexml.implementation.text.TextSenderThread.sendMessage(TextSenderThread.java:151)
	at org.jvoicexml.implementation.text.TextSenderThread.run(TextSenderThread.java:109)
2018-02-19 12:39:49,199 DEBUG TextSenderThread:136 - text sender thread stopped

??

See You

**Comment by mzamoun** [comment]
Other question : 
3) Can I start the browser with interactive mode ?
I mean : start the browser in line commande or in ( IHM ) and the browser make a sound when he found a prompt or wav, 
wait for input 
etc ...
?

**Comment by hotblac** [comment]
In response to your three questions:
1: The DemoIT is an example _integration_ test, not a unit test. It's configured to run in the Maven verify phase rather than test.
2. Is a known issue for the underlying JVoiceXML library. My apologies, but I've not yet logged or documented this. It does not affect test results as it occurs on test tear down.
3. VoiceXMLRiot does not support this. You may be better directly using JVoiceXML if you need access to an interactive voice browser.

**Comment by mzamoun** [comment]
Thank you for your reactivity 👍 

VoiceXMLRiot  use org.jvoicexml-0.7.7.GA.jar 

questions : 
1) I did not find the source of this jar in the web ? 
2) I think that I find a bug in resolving files. What do you think ?

See you soon.

If you want I can participate in your project to resolve some  bugs ...

**Comment by mzamoun** [comment]
JVoiceXmlApplication:258 - resolved to 'http://localhost:9090/voicexmlriot-junit-demo/vxml/***/***/***/***.js'

The path given by JVoiceXmlApplication is false !!

**Comment by mzamoun** [comment]
How can I help you ?

I have another question : 
The validator of js syntax is very strict ! and dont give me the line containing error !!

I have this error : 

org.mozilla.javascript.EvaluatorException: il manque ';' après une instruction (expr#15)
	at org.mozilla.javascript.DefaultErrorReporter.runtimeError(DefaultErrorReporter.java:77)
	at org.mozilla.javascript.DefaultErrorReporter.error(DefaultErrorReporter.java:64)
	at org.mozilla.javascript.Parser.addError(Parser.java:188)
	at org.mozilla.javascript.Parser.addWarning(Parser.java:152)

It tell me "Missing semicolon" but dont tell me where !!

See you

**Comment by hotblac** [comment]
I've found that too and I'm afraid I can't offer much advice other than systematically removing JavaScript sections until you find the cause.

If there's a way of making the Mozilla javascript engine print more useful messages, it would be worth including in VoiceXMLRiot. I'm not aware of one though so we just have to live with this as expected behavior.

**Comment by mzamoun** [comment]
I found a solution to the problem of ";" : 
I replaced characters accented by ascii characters in js files.

**Comment by mzamoun** [comment]
But The big problem is the resolving of the paths : it is not very clear !!??

**Comment by mzamoun** [comment]
Another error : 

2018-02-21 10:57:39,383 DEBUG ScriptStrategy:194 - evaluating internal script: var x = "rr";
	var y = 'kkk';
....
2018-02-21 10:57:39,403 WARN  EcmaScriptDataModel:934 - error evaluating 'var x = "rr";
	var y = 'kkk';
....
org.mozilla.javascript.EcmaError: SyntaxError: il manque ';' après une instruction (eval code#1(eval)#1)
	at org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java:3687)
	at org.mozilla.javascript.DefaultErrorReporter.error(DefaultErrorReporter.java:57)
	at org.mozilla.javascript.Parser.addError(Parser.java:188)
	at org.mozilla.javascript.Parser.addWarning(Parser.java:152)
	at org.mozilla.javascript.Parser.addStrictWarning(Parser.java:131)
	at org.mozilla.javascript.Parser.warnMissingSemi(Parser.java:3496)
	at org.mozilla.javascript.Parser.autoInsertSemicolon(Parser.java:1062)
	at org.mozilla.javascript.Parser.statementHelper(Parser.java:1044)
	at org.mozilla.javascript.Parser.statement(Parser.java:901)
	at org.mozilla.javascript.Parser.parse(Parser.java:540)
	at org.mozilla.javascript.Parser.parse(Parser.java:478)
	at org.mozilla.javascript.Context.compileImpl(Context.java:2348)
	at org.mozilla.javascript.Context.compileString(Context.java:1335)
	at org.mozilla.javascript.ScriptRuntime.evalSpecial(ScriptRuntime.java:2504)
	at org.mozilla.javascript.NativeGlobal.js_eval(NativeGlobal.java:496)
	at org.mozilla.javascript.NativeGlobal.execIdCall(NativeGlobal.java:157)
	at org.mozilla.javascript.IdFunctionObject.call(IdFunctionObject.java:97)
	at org.mozilla.javascript.ScriptRuntime.callSpecial(ScriptRuntime.java:2372)
	at org.mozilla.javascript.optimizer.OptRuntime.callSpecial(OptRuntime.java:131)
	at org.mozilla.javascript.gen.expr_3._c_log_debug_assignment_13(expr:153)
	at org.mozilla.javascript.gen.expr_3.call(expr)
	at org.mozilla.javascript.optimizer.OptRuntime.callName(OptRuntime.java:63)
	at org.mozilla.javascript.gen.expr_6._c_script_0(expr:7)
	at org.mozilla.javascript.gen.expr_6.call(expr)
	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:394)
	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3091)
	at org.mozilla.javascript.gen.expr_6.call(expr)
	at org.mozilla.javascript.gen.expr_6.exec(expr)
	at org.mozilla.javascript.Context.evaluateString(Context.java:1079)
	at org.jvoicexml.interpreter.datamodel.ecmascript.EcmaScriptDataModel.evaluateExpression(EcmaScriptDataModel.java:918)
	at org.jvoicexml.interpreter.datamodel.ecmascript.EcmaScriptDataModel.evaluateExpression(EcmaScriptDataModel.java:890)
	at org.jvoicexml.profile.vxml21.tagstrategy.ScriptStrategy.processInternalScript(ScriptStrategy.java:197)
	at org.jvoicexml.profile.vxml21.tagstrategy.ScriptStrategy.execute(ScriptStrategy.java:142)
	at org.jvoicexml.interpreter.VoiceXmlInterpreterContext.initDocument(VoiceXmlInterpreterContext.java:884)
	at org.jvoicexml.interpreter.VoiceXmlInterpreterContext.interpret(VoiceXmlInterpreterContext.java:821)
	at org.jvoicexml.interpreter.VoiceXmlInterpreterContext.process(VoiceXmlInterpreterContext.java:553)
	at org.jvoicexml.interpreter.JVoiceXmlSession.run(JVoiceXmlSession.java:402)
2018-02-21 10:57:39,406 INFO  ScopeObserver:106 - exiting scope 'document'...
2018-02-21 10:57:39,406 DEBUG ScopeObserver:120 - current scope stack: [SESSION, APPLICATION, APPLICATION]

**Comment by mzamoun** [comment]
What do you think about https://github.com/shekhargulati/java8-the-missing-tutorial/blob/master/10-nashorn.md ?

**Comment by mzamoun** [comment]
https://wiki.openjdk.java.net/display/Nashorn/Rhino+Migration+Guide

**Comment by hotblac** [comment]
The JavaScript engine is outside the remit of this project. All VoiceXML functionality is provided by the [JVoiceXML](https://github.com/JVoiceXML/JVoiceXML) library. which has chosen the Mozilla engine.

As the original issue raised works as expected, I'll close this ticket. If you've got general questions about VoiceXMLRiot, please contact me using the address in my profile. Or, for specific defects in VoiceXMLRiot, please raise a new ticket.

**Comment by mzamoun** [comment]
Just a note: Mozilla / rhino is also used in the pom of voicexmlriot-driver !!

**Comment by mzamoun** [comment]
Ok, but rhino is referenced inside your project also, not only in jvoicexml.
